### PR TITLE
Add format for big.mark and decimal.mark to tableone

### PR DESCRIPTION
**Pull request by ndevln**
Hi @kaz-yos,

Now I am hitting you with something bigger. I added format support to `print.ContTable` and `print.svyContTable`. Due to popular demand :) (#23, #51, #67)

Using formatOptions you can now control base::format to format all numbers. This also provides a possible solution to align IQR and SD values. 

It is not ready yet, but it resulted in 13 Test Failures, which I think are an improvement. There are 2 types of errors. 

1. Inf, Na and NaN are now better right aligned. 
2. When testing svyTableOne you run a test where the dependent and grouping variable are the same. This results in perfect separation with standard deviations equalling 0. When I run `oneway.test` the p-value is 0. In the old version an NA was printed, now it changes to <0.001. I think this is OK because this p-value is useless anyway. My only question is, if this was planned behaviour?

If it is ok, I will update the regression references. Next I will implement format for CatTables.

Greetings,
Alex

```
mwByEC1 <- svyCreateTableOne(vars = vars, strata = c("E","C1"), data = datSvy, factorVars = factorVars)
print(mwByEC1)

oneway.test(E ~ E:C1, data = datSvy$variables, var.equal = T)
```

Test Failure:
```
test-svyCreateTableOne.R:260: failure: printing of a svyTableOne object does not regress
print(mwByEC1_addOverall, printToggle = TRUE, test = TRUE, smd = TRUE) has changed from known value recorded in 'ref-svyTableOne_2StrataVars_addOverall_new'.
3/60 mismatches
x[44]: "<0.001"
y[44]: " NA"

x[56]: "   Inf"
y[56]: " Inf"

x[59]: "   NaN"
y[59]: " NaN"

```

Test Code:
```
contVars <- c("age","time","bili","trig","platelet","protime")
contTableBySexTrt <- CreateContTable(vars = contVars,
                                     strata = c("trt","sex"), data = pbc, addOverall =T)
print(contTableBySexTrt, nonnormal = contVars, formatOption = list(decimal.mark = "-", big.mark = "$"))
print(contTableBySexTrt, formatOption = list(decimal.mark = "-", big.mark = ""), smd = T, missing = T
```

### CODE REVIEW

**Comment by ndevln** [comment]
Adding this to `print.CatTable` and `print.svyCatTable` was easier. I got no additional test failure.

```
data(nhanes)
nhanesSvy <- svydesign(ids = ~ SDMVPSU, strata = ~ SDMVSTRA, weights = ~ WTMEC2YR, nest = TRUE, data = nhanes)
tab1 <- svyCreateTableOne(vars = c("HI_CHOL","race","agecat","RIAGENDR"),
                          strata = "RIAGENDR", data = nhanesSvy,
                          factorVars = c("race","RIAGENDR"))
print(tab1$CatTable, formatOption = list(decimal.mark = ".", big.mark = ",", justify = "right", trim=FALSE, scientific=F), missing = T, smd = T)
```

**Comment by ndevln** [comment]
Now it is fully implemented. print.TableOne() is working. And also n values are no formated. 

```
tableOne <- CreateTableOne(vars = vars, strata = c("sex"), data = do.call("rbind", replicate(50, pbc, simplify = FALSE)), addOverall = T)
print(tableOne, nonnormal = c("bili","chol","copper","alk.phos","trig"),
       exact = c("status","stage"), cramVars = "hepato", smd = TRUE, missing = T, 
      formatOptions = list(big.mark = ",", big.interval = 2))
```

There are now 3 additional test failures. These happen because the n of svy Tables is now rounded differently. The n is 405.015. In the old version sprintf converted ist to 405.01, now it is converted to 405.02.
```
print(mwOverall, printToggle = TRUE) has changed from known value recorded in 'ref-svyTableOne_overallPrint'.
1/6 mismatches
x[1]: "450.02"
y[1]: "450.01"
```

Last step is adding the Documentation.

**Comment by ndevln** [comment]
It seems to be done. Luckily there were tests, that made working a lot easier. And I had to touch a lot less Code than I thought.

Maybe tests should be added for this new functionality. But first tell me what you think :)

**Comment by kaz-yos** [comment]
@ndevln,  Thank you so much for such a big contribution to the long-standing issue.

I'm currently setting up some tests (rather "specs" in the describe/it style) to clarify the expected behavior of the format functions.
https://github.com/kaz-yos/tableone/commits/add_format

I have been wanting to set up this type of human-readable specs to guide further development. Now is a good opportunity to start. I'll let you know I clean up these additional commit on top of yours. I'll push them here if possible.

**Comment by kaz-yos** [comment]
It doesn't seem to be possible for me to push commits here. So I listed the additional changes I made to the PR below, which I will push after merging this PR. 

 5ca93f6 * origin/add_format Modify test files to reflect reference file$kaz-yos            10 minutes
 6d3c1da * Move reference rds files to a subfolder                       kaz-yos            12 minutes
 bbf8573 * Update test results with new formatter specs                  kaz-yos             2 days
 653d366 * Extend ModuleFormatPValues to handle decimal.mark             kaz-yos             2 days
 9139d3f * Avoid rounding means and medians early                        kaz-yos             2 days
 0e427bd * Refactor ModuleCatFormatVariables with ModuleFormatNumericVec$kaz-yos             2 days
 8e348b8 * Refactor functions with ModuleFormatNumericVector             kaz-yos             2 days
 6dac74e * Add ModuleFormatNumericVector                                 kaz-yos             2 days
 b3eaa29 * Add specs for format modules                                  kaz-yos             3 days
 d3044fc * Set default formatOptions = NULL for backward compatibility   kaz-yos             2 days
 96b6b71 * Clean white spaces                                            kaz-yos             2 days
 0da340c * Add back digits = digits when calling ModuleContFormatStrata $kaz-yos             2 days
 82db78a * Add back digits = digits when calling ModuleContFormatStrata $kaz-yos             2 days

The most important changes are the addition of the `ModuleFormatNumericVector` function 6dac74e and refactoring of other formatting functions to avoid raw calls to `format` 8e348b8. I think we will have easier time maintaining the code base this way.

**Comment by ndevln** [comment]
Your Tests are always incredibly thorough. This makes developing a lot easier.

And there are even 4 issues regarding this Topic. I forgot #20 in my first list.

**Pull request merged**
