### PR TITLE
Add Overall Column to stratified Tables. Close #12

### LINKED ISSUE #12: Total column
Great package- any chance you could include a addTotal=TRUE option for the grand total across strata?

### PR DESCRIPTION
**Pull request by ndevln**
Hi,

as requested in issue #12 I added an option to show an overall column for stratified tables.

I have tried to implement it without too many changes, while keeping the code readable. My solution is to run the Create*Table Function again without the strata statement and combining the results. Since `tableone` makes heavy use of attributes I reapply the strata name and factor level attributes. 

SMD and p-value calculation is done before using only the stratified columns and the corresponding attributes are applied after combining the results and is unaffected by the new column.

I had to make 1 change to a seemingly unrelated function. `ModuleReturnDimHeaders ` couldn't display the stratification variable, since the dimnames are not available any more after adding the overall column. But since strataVarName is always calculated at an earlier point, the function now uses this attribute.

For completeness the new option is also available for the svy*Table functions. 

I hope you like it. I am happy to make any changes you suggest.

Greetings,
Alexander Bartel

Example:
```
data(pbc)

## Make categorical variables factors
varsToFactor <- c("status","trt","ascites","hepato","spiders","edema","stage")
pbc[varsToFactor] <- lapply(pbc[varsToFactor], factor)

## Create a variable list
dput(names(pbc))
vars <- c("time","status","age","sex","ascites","hepato",
           "spiders","edema","bili","chol","albumin",
           "copper","alk.phos","ast","trig","platelet",
           "protime","stage")

tableOne <- CreateTableOne(vars = vars, strata = c("trt", "sex"), data = pbc, addOverall = T)
print(tableOne, nonnormal = c("bili","chol","copper","alk.phos","trig"),
       exact = c("status","stage"), cramVars = "hepato", smd = TRUE, missing = T)
```

```
                      Stratified by trt:sex
                       Overall                  1:m                      2:m                      1:f                      2:f                      p      test    SMD    Missing
  n                        418                       21                       15                      137                      139                                               
  time (mean (SD))     1917.78 (1104.67)        1793.48 (1244.70)        2156.33 (1428.56)        2049.67 (1070.20)        1979.65 (1127.52)         0.730          0.156  0.0   
  status (%)                                                                                                                                         0.024 exact    0.577  0.0   
     0                     232 (55.5)                 4 (19.0)                 7 (46.7)                79 ( 57.7)               78 ( 56.1)                                       
     1                      25 ( 6.0)                 3 (14.3)                 0 ( 0.0)                 7 (  5.1)                9 (  6.5)                                       
     2                     161 (38.5)                14 (66.7)                 8 (53.3)                51 ( 37.2)               52 ( 37.4)                                       
  age (mean (SD))        50.74 (10.45)            55.57 (12.61)            57.09 (10.07)            50.78 (10.65)            47.66 (9.54)           <0.001          0.521  0.0   
  sex = f (%)              374 (89.5)                 0 ( 0.0)                 0 ( 0.0)               137 (100.0)              139 (100.0)          <0.001          NaN    0.0   
  ascites = 1 (%)           24 ( 7.7)                 1 ( 4.8)                 2 (13.3)                13 (  9.5)                8 (  5.8)           0.516          0.176 25.4   
  hepato = 0/1 (%)     152/160 (48.7/51.3)         9/12 (42.9/57.1)          6/9 (40.0/60.0)        76/61 (55.5/44.5)        61/78 (43.9/56.1)       0.208          0.160 25.4   
  spiders = 1 (%)           90 (28.8)                 3 (14.3)                 1 ( 6.7)                42 ( 30.7)               44 ( 31.7)           0.089          0.402 25.4   
  edema (%)                                                                                                                                          0.906          0.212  0.0   
     0                     354 (84.7)                17 (81.0)                12 (80.0)               115 ( 83.9)              119 ( 85.6)                                       
     0.5                    44 (10.5)                 3 (14.3)                 1 ( 6.7)                13 (  9.5)               12 (  8.6)                                       
     1                      20 ( 4.8)                 1 ( 4.8)                 2 (13.3)                 9 (  6.6)                8 (  5.8)                                       
  bili (median [IQR])     1.40 [0.80, 3.40]        2.30 [1.40, 4.00]        1.90 [1.10, 2.85]        1.30 [0.80, 3.20]        1.30 [0.70, 3.60]      0.205 nonnorm  0.135  0.0   
  chol (median [IQR])   309.50 [249.50, 400.00]  376.00 [251.00, 456.00]  259.00 [235.75, 342.25]  309.00 [247.50, 399.50]  306.50 [258.00, 381.00]  0.458 nonnorm  0.295 32.1   
  trig (median [IQR])   108.00 [84.25, 151.00]   142.00 [107.00, 194.00]  108.50 [90.25, 137.00]   101.00 [84.00, 134.00]   113.00 [84.00, 157.00]   0.058 nonnorm  0.294 32.5   
  platelet (mean (SD))  257.02 (98.33)           232.65 (97.38)           240.13 (73.93)           262.59 (100.53)          267.95 (92.20)           0.362          0.234  2.6   
  protime (mean (SD))    10.73 (1.02)             10.84 (0.94)             11.23 (0.97)             10.62 (0.84)             10.75 (1.15)            0.137          0.328  0.5   
  stage (%)                                                                                                                                          NA    exact    0.277  1.4   
     1                      21 ( 5.1)                 2 ( 9.5)                 1 ( 6.7)                10 (  7.3)                3 (  2.2)                                       
     2                      92 (22.3)                 4 (19.0)                 2 (13.3)                31 ( 22.6)               30 ( 21.6)                                       
     3                     155 (37.6)                 7 (33.3)                 5 (33.3)                49 ( 35.8)               59 ( 42.4)                                       
     4                     144 (35.0)                 8 (38.1)                 7 (46.7)                47 ( 34.3)               47 ( 33.8)                                      
```

### CODE REVIEW

**Comment by kaz-yos** [comment]
This is really nice! I'm examining this locally.

Meanwhile, could you add some regression (degradation) tests to protect against future changes that break your contribution? They do not have to be extensive, but it would be nice if they cover functions that were modified.

The test files are under https://github.com/kaz-yos/tableone/tree/master/tests/testthat

**Comment by ndevln** [comment]
I'm happy to add tests. I will add them to this pull request.

**Comment by ndevln** [comment]
Hi,

while writing the tests I noticed that the strata labels when using the `summary()` function were missing. So I now added a fix for this problem. When using addOverall the strata names are:

- `sex: Overall` <- new
- `sex: m`
- `sex: f`

for 2 variable stratas the strata names are when using addOverall `trt:sex: Overall` or `trt:sex: 2:m` instead of:
```
trt: 2
sex: m
```

Luckily when trying to fix the summary.svy functions, I realized they were not broken. You already reapply the dimnames and the result is the same as mine. Everything is now consistent by accident :)

Finally, I added multiple test for the new addOverall option, including for using the summary function.

Greetings,
Alex

**Comment by kaz-yos** [comment]
Thank you so much for the great work! Travis-CI is having some funny environmental errors. Did your local test go OK. I'll examine the PR and Travis issues.

**Comment by ndevln** [comment]
Yes since Travis did fail I reran all tests.
```
== Results =====================================================================
Duration: 51.8 s

OK:       461
Failed:   0
Warnings: 0
Skipped:  0
```

The last changes were some refactoring and cleaning up. I realized that I could fix all attributes in the CreateCat/ContTable Functions. Because of that I removed all new code from summary.Cat/ContTable and moved it. I also created a new function to handle the reapplying of the attributes to reduce code duplication. Now it should be a lot more readable.

Luckily GitHub summarizes all the Commits.

**Comment by ndevln** [comment]
TravisCI works again :)

https://travis-ci.org/ndevln/tableone/builds/619530567

**Comment by ndevln** [comment]
Hi, 
sorry for the bad coding style. I accepted all changes. There is a batch commit option. But since I already committed some suggestions, I squashed them locally. 

Greetings
Alex

**Comment by kaz-yos** [comment]
Merged! Thank you for your contribution!!

**Comment by kaz-yos** [comment]
I realized somehow it has not been released on the CRAN. I probably forgot to confirm the CRAN submission confirmation email. I just resubmitted it.

**Comment by kaz-yos** [comment]
I got asked to prepare for the upcoming R 4.0.0 changes. So the CRAN release is being delayed.

**Comment by ndevln** [comment]
Thanks for the news. R 4.0.0 was already part of your TravisCI config, so everything should be fine.

Can I send you a PR to add my ORCID (0000-0002-1280-6138), since there is time left?

Best Wishes
Alex

**Comment by kaz-yos** [comment]
I can add it. So no need for another PR.

**Comment by ndevln** [comment]
Great. Thank you.

**Pull request merged**
